##Micronaut
micronaut:
  application:
    name: kafkaEngine
  server:
##Cors
    cors:
      enabled: true
    port: 8065
##Actuator
  endpoints:
    health:
      enabled: true
## Swagger
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
## Database
datasources:
  default:
    url: jdbc:postgresql://localhost:26257/shoes
    driverClassName: org.postgresql.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop

